"""add sub title to vbpl

Revision ID: 30a8cc2aa2e3
Revises: a7f7b1f0c007
Create Date: 2023-09-16 22:22:08.066169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30a8cc2aa2e3'
down_revision = 'a7f7b1f0c007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vbpl', sa.Column('sub_title', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vbpl', 'sub_title')
    # ### end Alembic commands ###
