"""add sector to vbpl

Revision ID: 39662aa4f371
Revises: b4d602eee5d6
Create Date: 2023-09-21 13:37:11.601530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39662aa4f371'
down_revision = 'b4d602eee5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vbpl', sa.Column('sector', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vbpl', 'sector')
    # ### end Alembic commands ###
