"""add big part field to vbpl

Revision ID: 442c32ff0fc8
Revises: 96514fe05609
Create Date: 2023-09-15 10:30:58.341826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '442c32ff0fc8'
down_revision = '96514fe05609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vbpl_toan_van', sa.Column('big_part_number', sa.String(length=25), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('big_part_name', sa.String(length=100), nullable=True))
    op.alter_column('vbpl_toan_van', 'chapter_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'part_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=25),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'mini_part_number',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.String(length=25),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vbpl_toan_van', 'mini_part_number',
               existing_type=sa.String(length=25),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'part_number',
               existing_type=sa.String(length=25),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'chapter_number',
               existing_type=sa.String(length=25),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=True)
    op.drop_column('vbpl_toan_van', 'big_part_name')
    op.drop_column('vbpl_toan_van', 'big_part_number')
    # ### end Alembic commands ###
