"""empty message

Revision ID: 753079bbc4eb
Revises: e3555761bf33
Create Date: 2023-09-11 21:27:43.924048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '753079bbc4eb'
down_revision = 'e3555761bf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
