"""add chapter part mini part to vbpl

Revision ID: 96514fe05609
Revises: e3555761bf33
Create Date: 2023-09-12 00:07:52.786522

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96514fe05609'
down_revision = 'e3555761bf33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vbpl_toan_van', sa.Column('chapter_number', sa.Integer(), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('chapter_name', sa.String(length=100), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('part_number', sa.Integer(), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('part_name', sa.String(length=100), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('mini_part_number', sa.Integer(), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('mini_part_name', sa.String(length=100), nullable=True))
    op.alter_column('vbpl_toan_van', 'section_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    op.drop_column('vbpl_toan_van', 'section_ref')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vbpl_toan_van', sa.Column('section_ref', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False))
    op.alter_column('vbpl_toan_van', 'section_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.drop_column('vbpl_toan_van', 'mini_part_name')
    op.drop_column('vbpl_toan_van', 'mini_part_number')
    op.drop_column('vbpl_toan_van', 'part_name')
    op.drop_column('vbpl_toan_van', 'part_number')
    op.drop_column('vbpl_toan_van', 'chapter_name')
    op.drop_column('vbpl_toan_van', 'chapter_number')
    # ### end Alembic commands ###
