"""add doc id to anle

Revision ID: a7f7b1f0c007
Revises: d3bce9a09db2
Create Date: 2023-09-15 11:07:43.725733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7f7b1f0c007'
down_revision = 'd3bce9a09db2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anle', sa.Column('doc_id', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('anle', 'doc_id')
    # ### end Alembic commands ###
