"""initial database

Revision ID: c7a8285ff499
Revises: 
Create Date: 2023-09-06 11:08:31.492194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7a8285ff499'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anle',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('file_link', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('adoption_date', sa.DateTime(), nullable=True),
    sa.Column('application_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('publication_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('publication_decision', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vbpl',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('file_link', sa.String(length=200), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('doc_type', sa.String(length=100), nullable=True),
    sa.Column('serial_number', sa.String(length=100), nullable=False),
    sa.Column('issuance_date', sa.DateTime(), nullable=True),
    sa.Column('effective_date', sa.DateTime(), nullable=True),
    sa.Column('expiration_date', sa.DateTime(), nullable=True),
    sa.Column('gazette_date', sa.DateTime(), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('issuing_authority', sa.String(length=100), nullable=True),
    sa.Column('applicable_information', sa.String(length=100), nullable=True),
    sa.Column('html', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('anle_section',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('anle_id', sa.Integer(), nullable=False),
    sa.Column('context', sa.String(length=1000), nullable=True),
    sa.Column('solution', sa.String(length=1000), nullable=True),
    sa.Column('content', sa.String(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['anle_id'], ['anle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vbpl_doc_map',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('doc_map_id', sa.Integer(), nullable=False),
    sa.Column('doc_map_type', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['doc_map_id'], ['vbpl.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['vbpl.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'doc_map_id')
    )
    op.create_table('vbpl_related_document',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['related_id'], ['vbpl.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['vbpl.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'related_id')
    )
    op.create_table('vbpl_toan_van',
    sa.Column('vbpl_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('section_ref', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['vbpl_id'], ['vbpl.id'], ),
    sa.PrimaryKeyConstraint('vbpl_id', 'section_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vbpl_toan_van')
    op.drop_table('vbpl_related_document')
    op.drop_table('vbpl_doc_map')
    op.drop_table('anle_section')
    op.drop_table('vbpl')
    op.drop_table('anle')
    # ### end Alembic commands ###
