"""add org pdf link and vbpl section content

Revision ID: e3555761bf33
Revises: c7a8285ff499
Create Date: 2023-09-09 16:30:49.074134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3555761bf33'
down_revision = 'c7a8285ff499'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('anle', sa.Column('org_pdf_link', sa.String(length=200), nullable=True))
    op.add_column('vbpl', sa.Column('org_pdf_link', sa.String(length=200), nullable=True))
    op.add_column('vbpl_toan_van', sa.Column('section_content', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vbpl_toan_van', 'section_content')
    op.drop_column('vbpl', 'org_pdf_link')
    op.drop_column('anle', 'org_pdf_link')
    # ### end Alembic commands ###
