"""add vbpl sub part table

Revision ID: f08ecc50eb1f
Revises: 39662aa4f371
Create Date: 2023-10-03 17:11:40.505272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f08ecc50eb1f'
down_revision = '39662aa4f371'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vbpl_sub_part',
    sa.Column('vbpl_id', sa.Integer(), nullable=False),
    sa.Column('sub_parts', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['vbpl_id'], ['vbpl.id'], ),
    sa.PrimaryKeyConstraint('vbpl_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vbpl_sub_part')
    # ### end Alembic commands ###
