"""finalize version

Revision ID: fb7812b9c3c6
Revises: f08ecc50eb1f
Create Date: 2023-10-09 17:17:41.470818

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fb7812b9c3c6'
down_revision = 'f08ecc50eb1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('anle', 'org_pdf_link',
               existing_type=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               type_=sa.String(length=1000),
               existing_nullable=True)
    op.alter_column('vbpl', 'file_link',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('vbpl', 'sub_title',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'chapter_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25),
               type_=sa.String(length=400),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'part_number',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25),
               type_=sa.String(length=400),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'part_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vbpl_toan_van', 'part_name',
               existing_type=sa.String(length=1000),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=200),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'part_number',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25),
               existing_nullable=True)
    op.alter_column('vbpl_toan_van', 'chapter_number',
               existing_type=sa.String(length=400),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25),
               existing_nullable=True)
    op.alter_column('vbpl', 'sub_title',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    op.alter_column('vbpl', 'file_link',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=1000),
               existing_nullable=True)
    op.alter_column('anle', 'org_pdf_link',
               existing_type=sa.String(length=1000),
               type_=mysql.TEXT(collation='utf8mb4_unicode_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###
